RDChampionship/Controllers/MatchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RDChampionship.Extensions;
using RDChampionship.Models;
using RDChampionship.Models.Logic;
using RDChampionship.Repositories.Contract;
using RDChampionship.Services.Identity;
using RDChampionship.Services.Implementation;

namespace RDChampionship.Controllers
{
    public class MatchController : Controller
    {
        // Properties
        public AppUserManager UserManager { get; set; }
        public IMatchRepository MatchRepository { get; set; }
        public ISetRepository SetRepository { get; set; }
        public IPointsRepository PointsRepository { get; set; }

        // Constructor
        public MatchController(AppUserManager userManager, IMatchRepository matchRepository, ISetRepository setRepository, IPointsRepository pointsRepository)
        {
            UserManager = userManager;
            MatchRepository = matchRepository;
            SetRepository = setRepository;
            PointsRepository = pointsRepository;
        }

        // Methods
        public ActionResult Index()
        {
            var vm = new MatchIndexViewModel
            {
                Matches = MatchRepository.GetAll(),
                Users = UserManager.Users.ToList(),
            };

            return View(vm);
        }

        public ActionResult Details(int id)
        {
            return View();
        }

        [Authorize]
        public ActionResult Create()
        {
            if (!User.IsAtLeastInOneRole(AppRoleService.Administrator, AppRoleService.Moderator, AppRoleService.FreeMatchPlayer))
            {
                return RedirectToAction("Error", "Home");
            }

            var vm = new MatchCreateViewModel
            {
                Users = UserManager.Users.ToList(),
            };

            return View(vm);
        }

        [HttpGet, Route("Match/ControlPanel/{matchId}")]
        public async Task<IActionResult> ControlPanel(Guid matchId)
        {
            var match = MatchRepository.Get(matchId);
            var set = SetRepository.GetCurrentSetForMatch(matchId);
            var allSets = SetRepository.GetSetsForMatch(matchId);
            var teamOnePlayerOne = await UserManager.FindByIdAsync(match.TeamOnePlayerOneId);
            var teamOnePlayerTwo = await UserManager.FindByIdAsync(match.TeamOnePlayerTwoId);
            var teamTwoPlayerOne = await UserManager.FindByIdAsync(match.TeamTwoPlayerOneId);
            var teamTwoPlayerTwo = await UserManager.FindByIdAsync(match.TeamTwoPlayerTwoId);

            var vm = new MatchControlPanelViewModel
            {
                Match = match,
                TeamOnePlayerOne = teamOnePlayerOne,
                TeamOnePlayerTwo = teamOnePlayerTwo,
                TeamTwoPlayerOne = teamTwoPlayerOne,
                TeamTwoPlayerTwo = teamTwoPlayerTwo,
            };

            if (set != null)
            {
                vm.TeamOnePoints = (int)set.TeamOnePoints;
                vm.TeamTwoPoints = (int)set.TeamTwoPoints;
            }
            vm.TeamOneSets = allSets.Count(s => s.WinnerTeam == TeamChoice.TeamOne);
            vm.TeamTwoSets = allSets.Count(s => s.WinnerTeam == TeamChoice.TeamTwo);

            return View(vm);
        }

        // --------------------------------------------------------------------------------------------------

        [HttpPost]
        public ActionResult Create(Match match)
        {
            if (!UserManager.Users.Any(user => user.Id == match.TeamOnePlayerOneId) ||
                !UserManager.Users.Any(user => user.Id == match.TeamOnePlayerTwoId) ||
                !UserManager.Users.Any(user => user.Id == match.TeamTwoPlayerOneId) ||
                !UserManager.Users.Any(user => user.Id == match.TeamTwoPlayerTwoId))
            {
                return RedirectToAction("Create");
            }

            // Is match has 4 diffrent players

            match.Created = DateTime.Now;

            MatchRepository.Create(match);

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public ActionResult Delete(Guid id)
        {
            var match = MatchRepository.Get(id);
            MatchRepository.Delete(match);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult StartMatch(Guid matchId)
        {
            var match = MatchRepository.Get(matchId);
            match.WinnerTeam = TeamChoice.None;
            match.Status = MatchStatus.During;
            MatchRepository.Update(match);

            var set = new Set
            {
                Created = DateTime.Now,
                MatchId = match.Id,
                Number = 0,
                IsEnded = false,
                TeamOnePoints = 0,
                TeamTwoPoints = 0,
            };
            SetRepository.Create(set);

            return RedirectToAction(nameof(ControlPanel), new { matchId });
        }

        [HttpPost]
        public IActionResult EndMatch(Guid matchId)
        {
            var match = MatchRepository.Get(matchId);
            var currentSet = SetRepository.GetCurrentSetForMatch(matchId);
            var sets = SetRepository.GetSetsForMatch(matchId);

            SummarizeAndEndSet(currentSet);
            SummarizeAndEndMatch(match, sets);
            SetRepository.Update(currentSet);
            MatchRepository.Update(match);

            return RedirectToAction($"ControlPanel", new { matchId });
        }

        [HttpPost]
        public IActionResult AddPoint(Guid matchId, string team)
        {
            var match = MatchRepository.Get(matchId);
            var set = SetRepository.GetCurrentSetForMatch(matchId);

            if (team == "one")
            {
                set.TeamOnePoints += 1;
            }
            else if (team == "two")
            {
                set.TeamTwoPoints += 1;
            }

            SetRepository.Update(set);

            return RedirectToAction($"ControlPanel", new { matchId });
        }

        [HttpPost]
        public IActionResult SubstractPoint(Guid matchId, string team)
        {
            var match = MatchRepository.Get(matchId);
            var set = SetRepository.GetCurrentSetForMatch(matchId);

            if (team == "one")
            {
                set.TeamOnePoints -= 1;
            }
            else if (team == "two")
            {
                set.TeamTwoPoints -= 1;
            }

            SetRepository.Update(set);

            return RedirectToAction($"ControlPanel", new { matchId, });
        }

        [HttpPost]
        public IActionResult NextSet(Guid matchId)
        {
            var match = MatchRepository.Get(matchId);
            var currentSet = SetRepository.GetCurrentSetForMatch(matchId);
            SummarizeAndEndSet(currentSet);
            SetRepository.Update(currentSet);

            var set = new Set
            {
                Created = DateTime.Now,
                IsEnded = false,
                MatchId = matchId,
                Number = currentSet.Number + 1,
            };
            SetRepository.Create(set);

            return RedirectToAction("ControlPanel", new { matchId, });
        }

        [HttpPost]
        public IActionResult PreviousSet(Guid matchId)
        {
            var match = MatchRepository.Get(matchId);
            var currentSet = SetRepository.GetCurrentSetForMatch(matchId);

            if (currentSet.Number > 0)
            {
                var previousSet = SetRepository.GetByNumber(matchId, currentSet.Number - 1);
                SetRepository.Delete(currentSet);
                previousSet.IsEnded = false;
                previousSet.WinnerTeam = TeamChoice.None;
                SetRepository.Update(previousSet);
            }

            return RedirectToAction("ControlPanel", new { matchId, });
        }

        public void SummarizeAndEndSet(Set set)
        {
            if (set.IsEnded)
            {
                throw new ArgumentException("Cannot summarize ended set.");
            }

            if (set.TeamOnePoints > set.TeamTwoPoints)
            {
                set.WinnerTeam = TeamChoice.TeamOne;
            }
            else if (set.TeamOnePoints < set.TeamTwoPoints)
            {
                set.WinnerTeam = TeamChoice.TeamTwo;
            }
            else
            {
                set.WinnerTeam = TeamChoice.TeamOneAndTeamTwo;
            }
            set.IsEnded = true;
        }

        public void SummarizeAndEndMatch(Match match, List<Set> sets)
        {
            int setsPointsTeamOne = sets.Count(s => s.WinnerTeam == TeamChoice.TeamOne);
            int setsPointsTeamTwo = sets.Count(s => s.WinnerTeam == TeamChoice.TeamTwo);

            if (setsPointsTeamOne > setsPointsTeamTwo)
            {
                match.WinnerTeam = TeamChoice.TeamOne;
            }
            else if (setsPointsTeamOne > setsPointsTeamTwo)
            {
                match.WinnerTeam = TeamChoice.TeamTwo;
            }
            else
            {
                match.WinnerTeam = TeamChoice.TeamOneAndTeamTwo;
            }

            match.SetPointsTeamOne = setsPointsTeamOne;
            match.SetPointsTeamTwo = setsPointsTeamTwo;
            match.Status = MatchStatus.Ended;
        }
    }
}

RDChampionship/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RDChampionship.Extensions;
using RDChampionship.Models;
using RDChampionship.Services.Identity;
using RDChampionship.Services.Implementation;

namespace RDChampionship.Controllers
{
    public class UsersController : Controller
    {
        // Services
        public AppUserManager UserManager { get; set; }

        // Constructor
        public UsersController(AppUserManager userManager)
        {
            UserManager = userManager;
        }

        // Methods
        public async Task<IActionResult> Details(string id)
        {
            var vm = new UserDetailsViewModel
            {
                User = await UserManager.FindByIdAsync(id),
            };

            return View(vm);
        }

        public IActionResult List()
        {
            var vm = new UserListViewModel
            {
                Users = UserManager.Users.ToList(),
            };

            return View(vm);
        }

        public async Task<IActionResult> Edit(string userId)
        {
            if (!User.IsAtLeastInOneRole(AppRoleService.Administrator, AppRoleService.Moderator))
            {
                return RedirectToAction("Error", "Home");
            }

            var user = await UserManager.FindByIdAsync(userId);

            if (user == null)
            {
                return RedirectToAction("Error", "Home");
            }

            return View(user);
        }

        [Authorize]
        public IActionResult Create()
        {
            if (!User.IsInRole(AppRoleService.Administrator))
            {
                return RedirectToAction("Error", "Home");
            }

            return View();
        }

        // --------------------------------------------------------------------------------------------------

        [HttpPost, Authorize]
        public async Task<IActionResult> Edit(AppUser user)
        {
            var userBeforeChange = await UserManager.FindByIdAsync(user.Id);

            if (string.IsNullOrWhiteSpace(user.UserName))
            {
                return RedirectToAction("Error", "Home"); // User should have not null or empty username
            }

            if (string.IsNullOrWhiteSpace(user.Email))
            {
                return RedirectToAction("Error", "Home"); // User should have not null or empty email
            }

            var u = await UserManager.FindByEmailAsync(user.Email);
            if (u != null)
            {
                return RedirectToAction("Error", "Home"); // User should have unique email
            }

            // Fields possible to update
            userBeforeChange.Email = user.Email;
            userBeforeChange.UserName = user.UserName;
            userBeforeChange.AvatarUrl = user.AvatarUrl;
            userBeforeChange.EmailConfirmed = user.EmailConfirmed;

            await UserManager.UpdateAsync(userBeforeChange);

            return RedirectToAction();
        }
    }
}

RDChampionship/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>RD Championship</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">RD Championship</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a asp-area="" asp-controller="Users" asp-action="List">Gracze</a></li>
                    }
                    <li><a asp-area="" asp-controller="Tournament" asp-action="Index">Turnieje</a></li>
                    <li><a asp-area="" asp-controller="Match" asp-action="Index">Mecze</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>
                &copy; 2019 - RD Projekt Championship - <a href="~/About/PrivacyPolicy">Polityka prywatności</a> <br />
                Kontakt: <a href="mailto:fabbbian@interia.pl">Fabian Oleksiuk: Fabbbian@interia.pl</a><br />
            </p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>