RDChampionship/Models/Logic/TournamentMatch.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RDChampionship.Models.Logic
{
    public class TournamentMatch : Match
    {
        public Guid TournamentId { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }
        public bool IsActive { get; set; }
    }
}

RDChampionship/Controllers/TournamentMatchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RDChampionship.Extensions;
using RDChampionship.Models;
using RDChampionship.Models.Logic;
using RDChampionship.Repositories.Contract;
using RDChampionship.Services.Contract;
using RDChampionship.Services.Identity;
using RDChampionship.Services.Implementation;

namespace RDChampionship.Controllers
{
    public class TournamentMatchController : Controller
    {
        // Properties
        public AppUserManager UserManager { get; set; }
        public ITournamentRepository TournamentRepository { get; set; }
        public IGroupRepository GroupRepository { get; set; }
        public ITournamentMatchRepository TournamentMatchRepository { get; set; }
        public ITeamRepository TeamRepository { get; set; }
        public IMatchRepository MatchRepository { get; set; }
        public ITournamentMatchControlService TournamentMatchControlService { get; set; }
        public IRegistrationRepository RegistrationRepository { get; set; }
        public IUserStatisticsService UserStatisticsService { get; set; }

        // Constructor
        public TournamentMatchController(AppUserManager userManager, ITournamentRepository tournamentRepository, IGroupRepository groupRepository,
            ITeamRepository teamRepository, ITournamentMatchRepository tournamentMatchRepository, IRegistrationRepository registrationRepository, 
            IMatchRepository matchRepository, ITournamentMatchControlService tournamentMatchControlService, IUserStatisticsService userStatisticsService)
        {
            UserManager = userManager;
            TournamentRepository = tournamentRepository;
            GroupRepository = groupRepository;
            TeamRepository = teamRepository;
            TournamentMatchRepository = tournamentMatchRepository;
            MatchRepository = matchRepository;
            RegistrationRepository = registrationRepository;

            TournamentMatchControlService = tournamentMatchControlService;
            UserStatisticsService = userStatisticsService;
        }

        // Methods
        public IActionResult Index(Guid tournamentId)
        {
            var vm = new TournamentMatchIndexViewModel
            {
                Tournament = TournamentRepository.Get(tournamentId),
                Matches = TournamentMatchRepository.GetAll(tournamentId),
                Users = UserManager.Users.ToList(),
            };

            return View(vm);
        }

        public IActionResult List(Guid tournamentId)
        {
            return RedirectToAction(nameof(Index), new { tournamentId });
        }

        [Authorize]
        public IActionResult MatchesAdministration(Guid tournamentId)
        {
            if (!User.IsAtLeastInOneRole(AppRoleService.Administrator, AppRoleService.Moderator))
            {
                return RedirectToAction("Home", "Error");
            }

            var vm = new TournamentMatchesAdministrationViewModel
            {
                Tournament = TournamentRepository.Get(tournamentId),
                Matches = TournamentMatchRepository.GetAll(tournamentId),
                Users = UserManager.Users.ToList(),
            };

            return View(vm);
        }

        public async Task<IActionResult> ControlPanel(Guid matchId)
        {
            var match = TournamentMatchRepository.Get(matchId);
            var vm = new TournamentMatchControlPanelViewModel
            {
                Match = match,
                MatchScore = TournamentMatchControlService.GetCurrentMatchScore(matchId),
            };

            vm.TeamOnePlayerOne = await UserManager.FindByIdAsync(match.TeamOnePlayerOneId);
            vm.TeamOnePlayerTwo = await UserManager.FindByIdAsync(match.TeamOnePlayerTwoId);
            vm.TeamTwoPlayerOne = await UserManager.FindByIdAsync(match.TeamTwoPlayerOneId);
            vm.TeamTwoPlayerTwo = await UserManager.FindByIdAsync(match.TeamTwoPlayerTwoId);

            string username = User.Identity.Name;
            if (vm.TeamOnePlayerOne.UserName == username || vm.TeamOnePlayerTwo.UserName == username ||
                vm.TeamTwoPlayerOne.UserName == username || vm.TeamTwoPlayerTwo.UserName == username)
            {
                vm.IsCurrentUserIsMatchPlayer = true;
            }
            else
            {
                vm.IsCurrentUserIsMatchPlayer = false;
            }

            return View(vm);
        }

        [Authorize]
        public IActionResult Create(Guid tournamentId)
        {
            if (!User.IsAtLeastInOneRole(AppRoleService.Administrator, AppRoleService.Moderator))
            {
                return RedirectToAction("Home", "Error");
            }

            var vm = new TournamentMatchCreateViewModel
            {
                TournamentMatch = new TournamentMatch
                {
                    TournamentId = tournamentId,
                    Name = "Mecz turniejowy",
                    StartTime = DateTime.Now.Date,
                    EndTime = DateTime.Now.AddDays(14).Date,
                },
            };

            // Select torunament participants
            vm.TournamentParticipants = new List<AppUser>();
            foreach (var user in UserManager.Users)
            {
                var registration = RegistrationRepository.Get(user.Id, tournamentId);
                if (registration != null)
                {
                    vm.TournamentParticipants.Add(user);
                }
            }

            return View(vm);
        }

        public IActionResult Edit(Guid matchId)
        {
            if (!User.IsAtLeastInOneRole(AppRoleService.Administrator, AppRoleService.Moderator))
            {
                return RedirectToAction("Error", "Home");
            }

            var match = TournamentMatchRepository.Get(matchId);

            var vm = new TournamentMatchEditViewModel()
            {
                TournamentMatch = match,
            };

            // Select torunament participants
            vm.TournamentParticipants = new List<AppUser>();
            foreach (var user in UserManager.Users)
            {
                var registration = RegistrationRepository.Get(user.Id, match.TournamentId);
                if (registration != null)
                {
                    vm.TournamentParticipants.Add(user);
                }
            }

            return View(vm);
        }

        // --------------------------------------------------------------------------------------------------

        [HttpPost, Authorize]
        public IActionResult Create(TournamentMatch match)
        {
            if (!User.IsAtLeastInOneRole(AppRoleService.Administrator, AppRoleService.Moderator))
            {
                return RedirectToAction("Error", "Home");
            }

            match.Created = DateTime.Now;
            TournamentMatchRepository.Create(match);
            return RedirectToAction(nameof(MatchesAdministration), new { tournamentId = match.TournamentId });
        }

        [HttpPost, Authorize]
        public IActionResult Edit(TournamentMatch match, Guid matchId)
        {
            var matchDb = TournamentMatchRepository.Get(matchId);

            matchDb.Name = match.Name;
            matchDb.Status = match.Status;
            matchDb.WinnerTeam = match.WinnerTeam;
            matchDb.IsActive = match.IsActive;
            matchDb.SetPointsTeamOne = match.SetPointsTeamOne;
            matchDb.SetPointsTeamTwo = match.SetPointsTeamTwo;
            matchDb.TeamOnePlayerOneId = match.TeamOnePlayerOneId;
            matchDb.TeamOnePlayerTwoId = match.TeamOnePlayerTwoId;
            matchDb.TeamTwoPlayerOneId = match.TeamTwoPlayerOneId;
            matchDb.TeamTwoPlayerTwoId = match.TeamTwoPlayerTwoId;

            TournamentMatchRepository.Update(matchDb);

            return RedirectToAction(nameof(Index), new { tournamentId = matchDb.TournamentId });
        }

        [HttpPost, Authorize]
        public IActionResult Delete(Guid matchId)
        {
            if (!User.IsInRole(AppRoleService.Administrator))
            {
                return RedirectToAction("Error", "Home");
            }

            var match = TournamentMatchRepository.Get(matchId);
            TournamentMatchRepository.Delete(match);
            return RedirectToAction(nameof(MatchesAdministration), new { match.TournamentId });
        }

        [HttpPost]
        public IActionResult StartMatch(Guid matchId)
        {
            if (!User.IsAtLeastInOneRole(AppRoleService.Administrator, AppRoleService.Moderator, AppRoleService.Participant))
            {
                return RedirectToAction("Error", "Home");
            }

            TournamentMatchControlService.StartMatch(matchId);

            return RedirectToAction($"ControlPanel", new { matchId });
        }

        [HttpPost]
        public IActionResult EndMatch(Guid matchId)
        {
            if (!User.IsAtLeastInOneRole(AppRoleService.Administrator, AppRoleService.Moderator, AppRoleService.Participant))
            {
                return RedirectToAction("Error", "Home");
            }

            TournamentMatchControlService.EndMatch(matchId);
            

            UserStatisticsService.SumStatisticsForTournamentMatch(UserManager.FindByNameAsync(User.Identity.Name).Result.Id, matchId);

            return RedirectToAction($"ControlPanel", new { matchId });
        }

        [HttpPost]
        public IActionResult AddPoint(Guid matchId, string team)
        {
            if (!User.IsAtLeastInOneRole(AppRoleService.Administrator, AppRoleService.Moderator, AppRoleService.Participant))
            {
                return RedirectToAction("Error", "Home");
            }

            TournamentMatchControlService.AddPoint(matchId, team);

RDChampionship/Views/TournamentMatch/ControlPanel.cshtml
@model TournamentMatchControlPanelViewModel

<h1>Mecz Turniejowy</h1>

<hr class="hidden-sm hidden-xs" />

<!-- Large view -->
<div class="row hidden-sm hidden-xs" style="margin-top: 20px;">
    <div class="col-md-1">

    </div>
    <div class="col-md-4 text-center">
        <div class="row">
            <div class="col-md-6 text-center">
                <a href="~/Users/Details/@Model.TeamOnePlayerOne.Id">
                    <img src="@Model.TeamOnePlayerOne.AvatarUrl" style="height: 75px;" />
                </a>
            </div>
            <div class="col-md-6 text-center">
                <a href="~/Users/Details/@Model.TeamOnePlayerTwo.Id">
                    <img src="@Model.TeamOnePlayerTwo.AvatarUrl" style="height: 75px;" />
                </a>
            </div>
            <div class="col-md-6 text-center">
                <a href="~/Users/Details/@Model.TeamOnePlayerOne.Id">
                    <h5>@Model.TeamOnePlayerOne.UserName</h5>
                </a>
            </div>
            <div class="col-md-6 text-center">
                <a href="~/Users/Details/@Model.TeamOnePlayerTwo.Id">
                    <h5>@Model.TeamOnePlayerTwo.UserName</h5>
                </a>
            </div>
            <div class="col-md-12">
                Sety: @Model.MatchScore.TeamOneSets
            </div>
            <div class="col-md-12">
                Punkty: @Model.MatchScore.TeamOnePoints
            </div>
        </div>
    </div>
    <div class="col-md-2 text-center align-middle" style="font-size: 35px; font-weight: 500;">
        <div class="hidden-xs"><br /></div>
        VS
    </div>
    <div class="col-md-4 text-center">
        <div class="row">
            <div class="col-md-6">
                <a href="~/Users/Details/@Model.TeamTwoPlayerOne.Id">
                    <img src="@Model.TeamTwoPlayerOne.AvatarUrl" style="height: 75px;" />
                </a>
            </div>
            <div class="col-md-6">
                <a href="~/Users/Details/@Model.TeamTwoPlayerTwo.Id">
                    <img src="@Model.TeamTwoPlayerTwo.AvatarUrl" style="height: 75px;" />
                </a>
            </div>
            <div class="col-md-6">
                <a href="~/Users/Details/@Model.TeamTwoPlayerOne.Id">
                    <h5>@Model.TeamTwoPlayerOne.UserName</h5>
                </a>
            </div>
            <div class="col-md-6">
                <a href="~/Users/Details/@Model.TeamTwoPlayerTwo.Id">
                    <h5>@Model.TeamTwoPlayerTwo.UserName</h5>
                </a>
            </div>
            <div class="col-md-12">
                Sety: @Model.MatchScore.TeamTwoSets
            </div>
            <div class="col-md-12">
                Punkty: @Model.MatchScore.TeamTwoPoints
            </div>
        </div>
    </div>
    <div class="col-md-1">

    </div>
</div>

<!-- Small View -->
<div class="row hidden-lg hidden-md" style="margin-top: 20px;">
    <div class="col-xs-6 text-center">
        <a href="~/Users/Details/@Model.TeamOnePlayerOne.Id">
            <h5>@Model.TeamOnePlayerOne.UserName</h5>
        </a>
        <a href="~/Users/Details/@Model.TeamOnePlayerTwo.Id">
            <h5>@Model.TeamOnePlayerTwo.UserName</h5>
        </a>
        Sety: @Model.MatchScore.TeamOneSets <br />
        Punkty: @Model.MatchScore.TeamOnePoints
    </div>
    <div class="col-xs-6 text-center">
        <a href="~/Users/Details/@Model.TeamTwoPlayerOne.Id">
            <h5>@Model.TeamTwoPlayerOne.UserName</h5>
        </a>
        <a href="~/Users/Details/@Model.TeamTwoPlayerTwo.Id">
            <h5>@Model.TeamTwoPlayerTwo.UserName</h5>
        </a>
        Sety: @Model.MatchScore.TeamTwoSets <br />
        Punkty: @Model.MatchScore.TeamTwoPoints
    </div>
</div>

<hr />

@if (Model.Match.Status == RDChampionship.Models.Logic.MatchStatus.Scheduled)
{
    <div class="row" style="margin-top: 30px;">
        <div class="col-md-12 text-center">
            @if (User.IsAtLeastInOneRole(AppRoleService.Administrator, AppRoleService.Moderator) ||
               (User.IsInRole(AppRoleService.Participant) && Model.IsCurrentUserIsMatchPlayer))
            {
                <form action="~/Match/StartMatch" method="post">
                    <input type="hidden" name="matchId" value="@Model.Match.Id" />
                    <button class="btn btn-primary" type="submit">Rozpocznij mecz</button>
                </form>
            }
        </div>
    </div>
}
else if (Model.Match.Status == RDChampionship.Models.Logic.MatchStatus.During)
{
    <hr />

    <div class="row">
        <div class="col-sm-2 col-md-2 col-lg-2">

        </div>
        <div class="col-sm-3 col-md-3 col-lg-3 text-center">
            @if (User.IsAtLeastInOneRole(AppRoleService.Administrator, AppRoleService.Moderator) ||
               (User.IsInRole(AppRoleService.Participant) && Model.IsCurrentUserIsMatchPlayer))
            {
                <form action="~/Match/AddPoint" method="post">
                    <input type="hidden" name="matchId" value="@Model.Match.Id" />
                    <input type="hidden" name="team" value="one" />
                    <button class="btn btn-primary" type="submit" style="width: 150px; margin: 5px;">Dodaj punkt (+)</button>
                </form>
                <form action="~/Match/SubstractPoint" method="post">
                    <input type="hidden" name="matchId" value="@Model.Match.Id" />
                    <input type="hidden" name="team" value="one" />
                    <button class="btn btn-primary" type="submit" style="width: 150px; margin: 5px;">Odejmij punkt (-)</button>
                </form>
            }


        </div>
        <div class="col-sm-2 col-md-2 col-lg-2 text-center align-middle" style="font-size: 40px; font-weight: 500;">
            <div class="hidden-xs"><br /></div>
        </div>
        <div class="col-sm-3 col-md-3 col-lg-3 text-center">
            @if (User.IsAtLeastInOneRole(AppRoleService.Administrator, AppRoleService.Moderator) ||
               (User.IsInRole(AppRoleService.Participant) && Model.IsCurrentUserIsMatchPlayer))
            {
                <form action="~/Match/AddPoint" method="post">
                    <input type="hidden" name="matchId" value="@Model.Match.Id" />
                    <input type="hidden" name="team" value="two" />
                    <button class="btn btn-danger" type="submit" style="width: 150px; margin: 5px;">Dodaj punkt (+)</button>
                </form>
                <form action="~/Match/SubstractPoint" method="post">
                    <input type="hidden" name="matchId" value="@Model.Match.Id" />
                    <input type="hidden" name="team" value="two" />
                    <button class="btn btn-danger" type="submit" style="width: 150px; margin: 5px;">Odejmij punkt (-)</button>
                </form>
            }
        </div>
        <div class="col-sm-2 col-md-2 col-lg-2">

        </div>
    </div>

    <br />

    <div class="row">
        <div class="col-md-12 text-center">
            @if (User.IsAtLeastInOneRole(AppRoleService.Administrator, AppRoleService.Moderator) ||
               (User.IsInRole(AppRoleService.Participant) && Model.IsCurrentUserIsMatchPlayer))
            {
                <form action="~/Match/NextSet" method="post">
                    <input type="hidden" name="matchId" value="@Model.Match.Id" />
                    <button class="btn btn-success" type="submit" style="width: 190px; margin: 5px;">Zakończ set</button>
                </form>
                <form action="~/Match/PreviousSet" method="post">
                    <input type="hidden" name="matchId" value="@Model.Match.Id" />
                    <button class="btn btn-success" type="submit" style="width: 190px; margin: 5px;">Przywróć poprzedni set</button>
                </form>
                <form action="~/Match/EndMatch" method="post">
                    <input type="hidden" name="matchId" value="@Model.Match.Id" />
                    <button class="btn btn-success" type="submit" style="width: 190px; margin: 5px;">Zakończ mecz</button>
                </form>
            }
        </div>
    </div>
}
else if (Model.Match.Status == RDChampionship.Models.Logic.MatchStatus.Ended)
{
    <br />

    <div class="row">
        <div class="col-md-12 text-center">
            <h3>Mecz zakończony!</h3>
        </div>
    </div>
}

RDChampionship/Views/TournamentMatch/Create.cshtml
@model TournamentMatchCreateViewModel

<h2>Stwórz mecz turniejowy</h2>

@{
    List<SelectListItem> userListForSelect = new List<SelectListItem>();
    foreach (var user in Model.TournamentParticipants)
    {
        userListForSelect.Add(new SelectListItem(user.UserName, user.Id));
    };
    userListForSelect.First().Selected = true;
}

<hr />

<div class="row">
    <form action="~/TournamentMatch/Create" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input name="TournamentId" type="hidden" asp-for="TournamentMatch.TournamentId" value="@Model.TournamentMatch.TournamentId" class="form-control" />

        <div class="row">
            <div class="col-md-6 form-group">
                <div class="form-group">
                    <label asp-for="TournamentMatch.Name" class="control-label"></label>
                    <input name="Name" asp-for="TournamentMatch.Name" class="form-control" />
                    <span asp-validation-for="TournamentMatch.Name" class="text-danger"></span>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <h3>Drużyna 1</h3>
                <div class="form-group">
                    <b>Gracz 1</b>
                    <select class="form-control" name="TeamOnePlayerOneId" asp-items="@userListForSelect" ></select>
                </div>
                <div class="form-group">
                    <b>Gracz 2</b>
                    <select class="form-control" name="TeamOnePlayerTwoId" asp-items="@userListForSelect" ></select>
                </div>
            </div>
            <div class="col-md-6">
                <h3>Drużyna 2</h3>

                <div class="form-group">
                    <b>Gracz 1</b>
                    <select class="form-control" name="TeamTwoPlayerOneId" asp-items="@userListForSelect" ></select>
                </div>
                <div class="form-group">
                    <b>Gracz 2</b>
                    <select class="form-control" name="TeamTwoPlayerTwoId" asp-items="@userListForSelect" ></select>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 form-group">
                <label asp-for="TournamentMatch.StartTime" class="control-label"></label>
                <input name="StartTime" asp-for="TournamentMatch.StartTime" class="form-control" />
                <span asp-validation-for="TournamentMatch.StartTime" class="text-danger"></span>
            </div>
            <div class="col-md-6 form-group">
                <label asp-for="TournamentMatch.EndTime" class="control-label"></label>
                <input name="EndTime" asp-for="TournamentMatch.EndTime" class="form-control" />
                <span asp-validation-for="TournamentMatch.EndTime" class="text-danger"></span>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 form-group">
                <div class="checkbox">
                    <label>
                        <input name="IsActive" asp-for="TournamentMatch.IsActive" />
                        @Html.DisplayNameFor(model => model.TournamentMatch.IsActive)
                    </label>
                </div>
            </div>
        </div>

        <div class="btn-group">
            <button class="btn btn-danger" type="submit">Stwórz</button>
            <a class="btn btn-primary" href="javascript:history.back()">Cofnij</a>
        </div>
    </form>
</div>

RDChampionship/Views/TournamentMatch/Index.cshtml
@model TournamentMatchIndexViewModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Mecze Turniejowe - @Model.Tournament.Name </h1>

@if (User.IsAtLeastInOneRole(AppRoleService.Administrator, AppRoleService.Moderator))
{
    @Html.ActionLink("Zarządzaj meczami", "MatchesAdministration", "TournamentMatch", new { tournamentId = Model.Tournament.Id }, new { @class = "btn btn-danger" })
}

<table class="table">
    <thead>
        <tr>
            <th>
                Nazwa
            </th>
            <th>
                Utworzono
            </th>
            <th>
                Drużyna I
            </th>
            <th>
                Drużyna II
            </th>
            <th>
                Status
            </th>
            <th>
                Obecny Wynik (Sety)
            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var match in Model.Matches)
        {
            var teamOnePlayerOne = Model.Users.FirstOrDefault(u => u.Id == match.TeamOnePlayerOneId);
            var teamOnePlayerTwo = Model.Users.FirstOrDefault(u => u.Id == match.TeamOnePlayerTwoId);
            var teamTwoPlayerOne = Model.Users.FirstOrDefault(u => u.Id == match.TeamTwoPlayerOneId);
            var teamTwoPlayerTwo = Model.Users.FirstOrDefault(u => u.Id == match.TeamTwoPlayerTwoId);

            <tr>
                <td>
                    @Html.DisplayFor(modelItem => match.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => match.Created)
                </td>
                <td>
                    @teamOnePlayerOne.UserName <br />
                    @teamOnePlayerTwo.UserName
                </td>
                <td>
                    @teamTwoPlayerOne.UserName <br />
                    @teamTwoPlayerTwo.UserName
                </td>
                <td>
                    @if (match.Status == RDChampionship.Models.Logic.MatchStatus.Scheduled)
                    {
                        <p>Oczekujący rozpoczęcia</p>
                    }
                    else if (match.Status == RDChampionship.Models.Logic.MatchStatus.During)
                    {
                        <p>Trwa obecnie</p>
                    }
                    else if (match.Status == RDChampionship.Models.Logic.MatchStatus.Suspended)
                    {
                        <p>Przerwany</p>
                    }
                    else if (match.Status == RDChampionship.Models.Logic.MatchStatus.Ended)
                    {
                        <p>Zakończony</p>
                    }
                    else
                    {
                        <p>Nieznany</p>
                    }
                </td>
                <td>
                    @match.SetPointsTeamOne : @match.SetPointsTeamTwo <br />
                </td>
                <td>
                    @Html.ActionLink("Panel meczu", "ControlPanel", "TournamentMatch", new { matchId = match.Id }, new { @class = "btn btn-primary" })
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="btn-group">
    @Html.ActionLink("Lista turniejów", "Index", "Tournament", null, new { @class = "btn btn-primary" })
</div>

RDChampionship/Views/TournamentMatch/MatchesAdministration.cshtml
@model TournamentMatchesAdministrationViewModel

<h2>Administracja meczami truniejowymi - @Model.Tournament.Name</h2>

<p style="margin-top: 30px; margin-bottom: 30px;">
    @Html.ActionLink("Utwórz nowy mecz", "Create", "TournamentMatch", new { tournamentId = Model.Tournament.Id }, new { @class = "btn btn-danger" })
</p>
<table class="table">
    <thead>
        <tr>
            <th> Nazwa </th>
            <th> Utworzono </th>
            <th> Drużyna I </th>
            <th> Drużyna II </th>
            <th> Status </th>
            <th> Wynik (Sety) </th>
            <th> </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var match in Model.Matches)
        {
            var teamOnePlayerOne = Model.Users.FirstOrDefault(u => u.Id == match.TeamOnePlayerOneId);
            var teamOnePlayerTwo = Model.Users.FirstOrDefault(u => u.Id == match.TeamOnePlayerTwoId);
            var teamTwoPlayerOne = Model.Users.FirstOrDefault(u => u.Id == match.TeamTwoPlayerOneId);
            var teamTwoPlayerTwo = Model.Users.FirstOrDefault(u => u.Id == match.TeamTwoPlayerTwoId);

            <tr>
                <td>
                    @Html.DisplayFor(modelItem => match.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => match.Created)
                </td>
                <td>
                    @teamOnePlayerOne.UserName <br />
                    @teamOnePlayerTwo.UserName
                </td>
                <td>
                    @teamTwoPlayerOne.UserName <br />
                    @teamTwoPlayerTwo.UserName
                </td>
                <td>
                    @if (match.Status == RDChampionship.Models.Logic.MatchStatus.Scheduled)
                    {
                        <p>Oczekujący rozpoczęcia</p>
                    }
                    else if (match.Status == RDChampionship.Models.Logic.MatchStatus.During)
                    {
                        <p>Trwa obecnie</p>
                    }
                    else if (match.Status == RDChampionship.Models.Logic.MatchStatus.Suspended)
                    {
                        <p>Przerwany</p>
                    }
                    else if (match.Status == RDChampionship.Models.Logic.MatchStatus.Ended)
                    {
                        <p>Zakończony</p>
                    }
                    else
                    {
                        <p>Nieznany</p>
                    }
                </td>
                <td>
                    @match.SetPointsTeamOne : @match.SetPointsTeamTwo <br />
                </td>
                <td>
                    <div class="btn-group">
                        @Html.ActionLink("Panel meczu", "ControlPanel", "TournamentMatch", new { matchId = match.Id }, new { @class = "btn btn-primary" });
                        @Html.ActionLink("Edytuj", "Edit", "TournamentMatch", new { matchId = match.Id }, new { @class = "btn btn-danger" });
                        <button onclick="document.getElementById('DeleteMatchForm-@match.Id').submit()" class="btn btn-danger">Usuń</button>
                    </div>

                    <form action="~/TournamentMatch/Delete" method="post" id="DeleteMatchForm-@match.Id">
                        <input type="hidden" name="matchId" value="@match.Id" />
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="btn-group">
    @Html.ActionLink("Lista turniejów", "Index", "Tournament", null,  new { @class = "btn btn-primary" })
</div>