RDChampionship/Models/Logic/Tournament.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace RDChampionship.Models.Logic
{
    public class Tournament
    {
        public Guid Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public DateTime Created { get; set; }
        [Required]
        public DateTime StartDate { get; set; }
        [Required]
        public DateTime SignInEndDate { get; set; }
        [Required]
        public DateTime EndDate { get; set; }
        [Required]
        public string LogoUrl { get; set; }
        public string Description { get; set; }
        [Required, Url]
        public string RulesPageUrl { get; set; }
        public TournamentPhase Phase { get; set; }
    }
}

RDChampionship/Controllers/RankingController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using RDChampionship.Models;
using RDChampionship.Models.Logic;
using RDChampionship.Repositories.Contract;
using RDChampionship.Services.Contract;

namespace RDChampionship.Controllers
{
    public class RankingController : Controller
    {
        // Properties
        public ITeamRepository TeamRepository { get; set; }
        public ITournamentRepository TournamentRepository { get; set; }
        public IGroupRepository GroupRepository { get; set; }
        public IGroupTeamsRepository GroupTeamsRepository { get; set; }
        public ITournamentMatchRepository MatchRepository { get; set; }
        public IRegistrationRepository RegistrationRepository { get; set; }
        public IPlayersRankingService RankingCalculator { get; set; }

        // Constructor
        public RankingController(ITeamRepository teamr, ITournamentRepository tr, IGroupRepository gr, 
            IGroupTeamsRepository gtr, ITournamentMatchRepository mr, IRegistrationRepository rr, IPlayersRankingService prs)
        {
            TeamRepository = teamr;
            TournamentRepository = tr;
            GroupRepository = gr;
            GroupTeamsRepository = gtr;
            MatchRepository = mr;
            RegistrationRepository = rr;
            RankingCalculator = prs;
        }

        // Methods
        public IActionResult Index(Guid tournamentId, RankingSortKey sortKey=RankingSortKey.PointsDescending)
        {
            var vm = new PointsTableIndexViewModel();
            vm.Tournament = TournamentRepository.Get(tournamentId);
            vm.TableData = RankingCalculator.CalculateRanking(vm.Tournament.Id, sortKey);

            return View(vm);
        }

        public IActionResult Groups(Guid tournamentId)
        {
            var vm = new EliminationTableGroupsViewModel
            {
                Groups = GroupRepository.GetActiveGroupsForTournament(tournamentId),
            };

            return View(vm);
        }

        public IActionResult GroupTable(Guid tournamentId, Guid groupId)
        {
            var vm = new EliminationTableGroupTableViewModel
            {
                Tournament = TournamentRepository.Get(tournamentId),
                Group = GroupRepository.Get(groupId),
                // Teams = TeamRepository.GetRegisteredTeams(tournamentId),
                // Matches = MatchRepository.GetActiveMatchesForGroup(tournamentId, groupId),
            };

            return View(vm);
        }

        public IActionResult Administration(Guid tournamentId)
        {
            var vm = new EliminationTableAdministrationViewModel
            {
                Tournament = TournamentRepository.Get(tournamentId),
                // RegisteredTeams = TeamRepository.GetRegisteredTeams(tournamentId),
                Groups = GroupRepository.GetActiveGroupsForTournament(tournamentId),
                Matches = new List<TournamentMatch>(),
            };

            foreach (var group in vm.Groups)
            {
                // var matches = MatchRepository.GetActiveMatchesForGroup(tournamentId, group.Id);
                // vm.Matches.AddRange(matches);
            }

            return View(vm);
        }

        // --------------------------------------------------------------------------------------------------

        [HttpPost]
        public IActionResult RandomizeGroups(Guid tournamentId, int groupsCount)
        {
            // var tournamentSettings = MatchRandomizer.RandomMatches(tournamentId, groupsCount);

            var tournament = TournamentRepository.Get(tournamentId);
            tournament.Phase = TournamentPhase.Championship;
            TournamentRepository.Update(tournament);

            return RedirectToAction($"MatchesAdministration", new { tournamentId });
        }
    }
}

RDChampionship/Controllers/TournamentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RDChampionship.Extensions;
using RDChampionship.Models;
using RDChampionship.Models.Logic;
using RDChampionship.Repositories.Contract;
using RDChampionship.Services.Contract;
using RDChampionship.Services.Identity;
using RDChampionship.Services.Implementation;

namespace RDChampionship.Controllers
{
    public class TournamentController : Controller
    {
        // Services
        public AppUserManager UserManager { get; set; }
        public ITournamentRepository TournamentRepository { get; set; }
        public ITournamentMatchRepository TournamentMatchRepository { get; set; }
        public IRegistrationRepository RegistrationRepository { get; set; }

        // Constructor
        public TournamentController(AppUserManager um, ITournamentRepository tr, IRegistrationRepository rr, ITournamentMatchRepository tmr)
        {
            UserManager = um;
            TournamentRepository = tr;
            RegistrationRepository = rr;
            TournamentMatchRepository = tmr;
        }

        // Methods
        public IActionResult Index()
        {
            var vm = new TournamentIndexViewModel
            {
                Tournaments = TournamentRepository.GetAll(),
            };

            return View(vm);
        }

        public IActionResult RegisteredUsers(Guid tournamentId)
        {
            var vm = new TournamentRegisteredUsersViewModel
            {
                TournamentId = tournamentId,
                Registrations = RegistrationRepository.GetAll(tournamentId),
                Users = UserManager.Users.ToList(),
            };

            return View(vm);
        }

        [Authorize]
        public IActionResult Create()
        {
            if (!User.IsAtLeastInOneRole(AppRoleService.Administrator, AppRoleService.Moderator))
            {
                return RedirectToAction("Home", "Error");
            }

            return View();
        }

        [Authorize, Route("/Tournament/Edit/{tournamentId}")]
        public IActionResult Edit(Guid tournamentId)
        {
            if (!User.IsAtLeastInOneRole(AppRoleService.Administrator, AppRoleService.Moderator))
            {
                return RedirectToAction("Home", "Error");
            }

            var tournament = TournamentRepository.Get(tournamentId);
            return View(tournament);
        }

        /// <summary> Provides functionality of sign in another users by admins or moderators. </summary>
        [Authorize]
        public IActionResult SignUpUser(Guid tournamentId)
        {
            if (!User.IsAtLeastInOneRole(AppRoleService.Administrator, AppRoleService.Moderator))
            {
                return RedirectToAction("Home", "Error");
            }

            var vm = new TournamentSignUpUserViewModel()
            {
                TournamentId = tournamentId,
                Users = UserManager.Users.ToList(),
            };

            return View(vm);
        }

        [Authorize]
        public IActionResult SignInProcessedSuccesfully()
        {
            if (!User.IsAtLeastInOneRole(AppRoleService.Administrator, AppRoleService.Moderator, AppRoleService.Participant))
            {
                return RedirectToAction("Home", "Error");
            }

            var vm = new TournamentSignInProcessedSuccesfullyViewModel();
            return View(vm);
        }

        [Authorize]
        public IActionResult UserAlredySignedIn()
        {
            if (!User.IsAtLeastInOneRole(AppRoleService.Administrator, AppRoleService.Moderator, AppRoleService.Participant))
            {
                return RedirectToAction("Home", "Error");
            }

            return View();
        }

        [Authorize]
        public IActionResult UserSignedOut()
        {
            if (!User.IsAtLeastInOneRole(AppRoleService.Administrator, AppRoleService.Moderator, AppRoleService.Participant))
            {
                return RedirectToAction("Home", "Error");
            }

            return View();
        }

        // --------------------------------------------------------------------------------------------------

        [HttpPost, Authorize]
        public IActionResult Create(Tournament tournament)
        {
            if (!User.IsAtLeastInOneRole(AppRoleService.Administrator))
            {
                return RedirectToAction("Home", "Error");
            }

            // TODO: Validate Tournament
            TournamentRepository.Create(tournament);
            return RedirectToAction("Index");
        }

        [HttpPost, Authorize]
        public IActionResult Edit(Tournament tournament)
        {
            if (!User.IsAtLeastInOneRole(AppRoleService.Administrator, AppRoleService.Moderator))
            {
                return RedirectToAction("Error", "Home");
            }

            // TODO: Validate Tournament
            TournamentRepository.Update(tournament);
            return RedirectToAction("Index");
        }

        [HttpPost, Authorize]
        public IActionResult Delete(Guid tournamentId)
        {
            if (!User.IsAtLeastInOneRole(AppRoleService.Administrator))
            {
                return RedirectToAction("Error", "Home");
            }

            var tournament = TournamentRepository.Get(tournamentId);
            TournamentRepository.Delete(tournament);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost, Authorize]
        public async Task<IActionResult> UserSignIn(Guid tournamentId, string username)
        {
            if (!User.IsAtLeastInOneRole(AppRoleService.Administrator, AppRoleService.Moderator, AppRoleService.Participant))
            {
                return RedirectToAction("Home", "Error");
            }

            if (!User.IsAtLeastInOneRole(AppRoleService.Administrator, AppRoleService.Moderator) && !string.IsNullOrWhiteSpace(username))
            {
                return RedirectToAction("Home", "Error"); // Another user cannot be signed in tournament by other roles than admin or moderator.
            }

            string usernameToSignIn = User.Identity.Name; 
            if (!string.IsNullOrWhiteSpace(username))
            {
                usernameToSignIn = username;
            }
            var user = await UserManager.FindByNameAsync(usernameToSignIn);
            var tournament = TournamentRepository.Get(tournamentId);

            if (!RegistrationRepository.IsUserRegisteredForTournament(user.Id, tournamentId))
            {
                var registration = new RegistrationForTournament
                {
                    UserId = user.Id,
                    TournamentId = tournament.Id
                };

                RegistrationRepository.Create(registration);
            }
            else
            {
                return RedirectToAction(nameof(UserAlredySignedIn));
            }

            return RedirectToAction(nameof(RegisteredUsers), new { tournamentId });
        }

        [HttpPost, Authorize]
        public async Task<IActionResult> UserSignOut(Guid tournamentId, string username)
        {
            if (!User.IsAtLeastInOneRole(AppRoleService.Administrator, AppRoleService.Moderator) && !string.IsNullOrWhiteSpace(username))
            {
                return RedirectToAction("Home", "Error"); // Another user cannot be signed in tournament by other roles than admin or moderator.
            }

            string usernameToSignOut = User.Identity.Name;
            if (!string.IsNullOrWhiteSpace(username))
            {
                usernameToSignOut = username;
            }
            var user = await UserManager.FindByNameAsync(usernameToSignOut);

            if (RegistrationRepository.IsUserRegisteredForTournament(user.Id, tournamentId))
            {
                RegistrationRepository.Delete(user.Id, tournamentId);
            }

            return RedirectToAction(nameof(RegisteredUsers), new { tournamentId });
        }
    }
}

RDChampionship/Views/Tournament/Create.cshtml
@model RDChampionship.Models.Logic.Tournament

<h1>Stwórz Nowy Turniej</h1>
<hr />
<form action="~/Tournament/Create" method="post">
    <div class="row">
        <div class="col-md-6">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <b>Nazwa Turnieju</b>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <b>Url - logo turnieju</b>
                <input asp-for="LogoUrl" class="form-control" />
                <span asp-validation-for="LogoUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <b>Url - Regulamin turnieju</b>
                <input asp-for="RulesPageUrl" class="form-control" />
                <span asp-validation-for="RulesPageUrl" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <b>Data początek zapisów</b>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <b>Data końca zapisów</b>
                <input asp-for="SignInEndDate" class="form-control" />
                <span asp-validation-for="SignInEndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <b>Data zakończenia turnieju</b>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <b>Opis</b>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <a asp-action="Index" class="btn btn-primary">Cofnij</a>
                <input type="submit" value="Utwórz" class="btn btn-danger" />
            </div>
        </div>
    </div>
</form>

RDChampionship/Views/Tournament/Edit.cshtml
@model RDChampionship.Models.Logic.Tournament

<h1>Edycja Turnieju</h1>
<hr />
<div class="row">
    <div class="col-md-12">
        <form action="~/Tournament/Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="Created" />
            <div class="row">
                <div class="col-md-6">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <b>Nazwa Turnieju</b>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <b>Url - logo turnieju</b>
                        <input asp-for="LogoUrl" class="form-control" />
                        <span asp-validation-for="LogoUrl" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <b>Url - Regulamin turnieju</b>
                        <input asp-for="RulesPageUrl" class="form-control" />
                        <span asp-validation-for="RulesPageUrl" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <b>Data początek zapisów</b>
                        <input asp-for="StartDate" class="form-control" />
                        <span asp-validation-for="StartDate" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <b>Data końca zapisów</b>
                        <input asp-for="SignInEndDate" class="form-control" />
                        <span asp-validation-for="SignInEndDate" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <b>Data zakończenia turnieju</b>
                        <input asp-for="EndDate" class="form-control" />
                        <span asp-validation-for="EndDate" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <b>Faza turnieju</b> <br />
                        <select asp-for="Phase" asp-items="Html.GetEnumSelectList<TournamentPhase>()">
                            <option selected="selected" value="">Wybierz fazę turnieju</option>
                        </select> 
                        <span asp-validation-for="Phase" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <b>Opis</b>
                        <textarea asp-for="Description" class="form-control"></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="form-group btn-group">
                @Html.ActionLink("Cofnij", "Index", "Tournament", null, new { @class = "btn btn-primary" })
                <input type="submit" value="Zapisz" class="btn btn-danger" />
            </div>
        </form>
    </div>
</div>

RDChampionship/Views/Tournament/Index.cshtml
@model TournamentIndexViewModel

@inject AppUserManager UserManager

<h1>Lista Turniejów</h1>

@if (User.Identity.IsAuthenticated)
{
    @if (User.IsInRole(AppRoleService.Administrator) || (User.IsInRole(AppRoleService.Moderator)))
    {
        <a href="~/Tournament/Create" class="btn btn-danger">Stwórz Nowy Turniej</a>
    }
}

@foreach (var tournament in Model.Tournaments)
{
    <hr />

    <div class="row">
        <div class="col-md-6 text-center">
            <img style="width: 48%; margin-top:23px; margin-bottom: 20px;" src="@tournament.LogoUrl" alt="Logo" />
            <p>
                @tournament.Description
            </p>
        </div>
        <div class="col-md-6">
            <h2>@tournament.Name</h2>

            @if (tournament.Phase == TournamentPhase.NotStarted)
            {
                <p>Turniej zaplanowany - rejstracja niebawem się rozpocznie.</p>
            }
            else if (tournament.Phase == TournamentPhase.Registration)
            {
                <p>Trwają zapisy na turniej.</p>
            }
            else if (tournament.Phase == TournamentPhase.Championship)
            {
                <p>Turniej się rozpoczął.</p>
            }
            else if (tournament.Phase == TournamentPhase.Ended)
            {
                <p>Turniej zakończony</p>
            }
            else
            {
            }

            @if (tournament.Phase == TournamentPhase.NotStarted || tournament.Phase == TournamentPhase.Registration)
            {
                <div>
                    Zapisy od @tournament.StartDate.ToShortDateString() godz. @tournament.StartDate.ToShortTimeString() <br />
                    Zapisy do @tournament.SignInEndDate.ToShortDateString() godz. @tournament.SignInEndDate.ToShortTimeString() <br />
                </div>
            }

            Zakończenie turnieju: @tournament.EndDate.ToShortDateString() godz. @tournament.EndDate.ToShortTimeString()  <br />

            <div style="margin-top: 20px; margin-bottom: 20px;">
                <form action="~/Tournament/UserSignIn" method="post">
                    <input type="hidden" id="tournamentId" name="tournamentId" value="@tournament.Id" />
                    <div class="btn-group text-center">
                        <a href="@tournament.RulesPageUrl" class="btn btn-info">Regulamin</a>
                        @if (User.Identity.IsAuthenticated &&
                       User.IsAtLeastInOneRole(AppRoleService.Administrator, AppRoleService.Participant) &&
                       tournament.Phase == TournamentPhase.Registration)
                        {
                            <button class="btn btn-primary" type="submit">Weź udział</button>
                        }
                        @Html.ActionLink("Uczestnicy", "RegisteredUsers", "Tournament", new { tournamentId = tournament.Id }, new { @class = "btn btn-primary" })

                        @if (tournament.Phase == TournamentPhase.Championship || tournament.Phase == TournamentPhase.Ended ||
                           User.IsAtLeastInOneRole(AppRoleService.Administrator, AppRoleService.Participant))
                        {
                            @Html.ActionLink("Mecze", "List", "TournamentMatch", new { tournamentId = tournament.Id }, new { @class = "btn btn-primary" })
                        }
                        @Html.ActionLink("Tabela", "Index", "Ranking", new { tournamentId = tournament.Id }, new { @class = "btn btn-primary" })
                    </div>
                </form>

                @if (!User.Identity.IsAuthenticated)
                {
                    <p style="margin-top: 20px; margin-bottom: 20px;">
                        <b>Zaloguj się zaby wziąć udział w turnieju</b>
                    </p>
                }

                @if (User.Identity.IsAuthenticated && !User.HasEmailConfirmed(UserManager))
                {
                    <p style="margin-top: 20px; margin-bottom: 20px;">
                        <b>Potwierdź adres email, aby wziąć udział w turnieju.</b>
                    </p>
                }

                @if (User.Identity.IsAuthenticated)
                {
                    @if (User.IsInRole(AppRoleService.Administrator) || User.IsInRole(AppRoleService.Moderator))
                    {
                        <h3>Administracja</h3>

                        <div class="btn-group">
                            @Html.ActionLink("Zarządzaj meczami", "MatchesAdministration", "TournamentMatch", new { tournamentId = tournament.Id }, new { @class = "btn btn-danger" })
                            @Html.ActionLink("Edytuj turniej", "Edit", "Tournament", new { tournamentId = tournament.Id }, new { @class = "btn btn-danger" })
                            <button class="btn btn-danger" onclick="document.getElementById('DeleteTournamnetForm').submit()">Usuń</button>
                        </div>

                        <form action="~/Tournament/Delete" method="post" id="DeleteTournamnetForm">
                            <input type="hidden" name="tournamentId" value="@tournament.Id" />
                        </form>
                    }
                }
            </div>
        </div>
    </div>
}

RDChampionship/Views/Tournament/RegisteredUsers.cshtml
@model TournamentRegisteredUsersViewModel

<h2>Użytkownicy zapisani na turniej [@Model.TournamentId] </h2>

@if (User.IsAtLeastInOneRole(AppRoleService.Administrator, AppRoleService.Moderator))
{
    <p style="margin-top: 20px; margin-bottom: 20px;">
        @Html.ActionLink("Zapisz użytkownika", "SignUpUser", "Tournament", new { tournamentId = Model.TournamentId }, new { @class = "btn btn-danger" })
    </p>
}

<table class="table">
    <thead>
        <tr>
            <th class="text-center">
            </th>
            <th class="text-center">
                Nazwa
            </th>
            <th class="text-center">
                Email
            </th>
            <th class="text-center">
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var registration in Model.Registrations)
        {
            var user = Model.Users.FirstOrDefault(u => u.Id == registration.UserId);
            <tr>
                <td scope="row" class="text-center">
                    @if (string.IsNullOrWhiteSpace(user.AvatarUrl))
                    {
                        <img src="~/images/avatar_empty.png" style="height:40px;" />
                    }
                    else
                    {
                        <img src="@user.AvatarUrl" style="height:40px;" />
                    }
                </td>
                <td scope="row" class="text-center">
                    @Html.DisplayFor(modelItem => user.UserName)
                </td>
                <td scope="row" class="text-center">
                    @Html.DisplayFor(modelItem => user.Email)
                </td>
                <td scope="row" class="text-center">
                    @if (User.IsAtLeastInOneRole(AppRoleService.Administrator, AppRoleService.Moderator))
                    {
                        <form action="~/Tournament/UserSignOut" method="post">
                            <input type="hidden" name="tournamentId" value="@Model.TournamentId" />
                            <input type="hidden" name="username" value="@user.UserName" />
                            <button class="btn btn-danger" type="submit">Wypisz</button>
                        </form>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

<a class="btn btn-primary" href="~/Tournament">Cofnij do listy turniejów</a>

RDChampionship/Views/Tournament/SignInProcessedSuccesfully.cshtml
@model TournamentSignInProcessedSuccesfullyViewModel


<h2>Potwierdzenie zapisu na mistrzostwa</h2>

Pomyślnie zapisałeś/aś się na turniej. <br/>

<a href="~/Tournament/Index">Lista turniejów</a>

RDChampionship/Views/Tournament/SignUpUser.cshtml
@model TournamentSignUpUserViewModel

@{
    ViewData["Title"] = "SignUpUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Zapisz użytkownika</h2>

<p>
    Zapisz użytkownika na mistrzostwa [@Model.TournamentId]
</p>

<form action="~/Tournament/UserSignIn" method="post">
    <input name="tournamentId" type="hidden" value="@Model.TournamentId"/>
    @{ 
        List<SelectListItem> userListForSelect = new List<SelectListItem>();
        foreach (var user in Model.Users)
        {
            userListForSelect.Add(new SelectListItem(user.UserName, user.UserName));
        };
        userListForSelect.First().Selected = true;
    }

    <select name="username" asp-items="@userListForSelect"></select>

    <br/>

    <div style="margin-top: 20px;" class="btn-group">
        <button type="submit" class="btn btn-danger">Zapisz użytkownika</button>
        @Html.ActionLink("Cofnij do listy zapisanych użytkowników", "RegisteredUsers", "Tournament", new { tournamentId = Model.TournamentId }, new { @class = "btn btn-primary" })
    </div>    
</form>

RDChampionship/Views/Tournament/UserAlredySignedIn.cshtml
<h2>Nie można się ponownie zapisać</h2>

Użytkownik został wcześniej zapisany na ten turniej. <br/>

<a href="~/Tournament/Index">Lista turniejów</a>

RDChampionship/Views/Tournament/UserSignedOut.cshtml
<h2>Użytkownik wypisany</h2>

Użytkownik został wypisany z mistrzostw. <br/>

<a href="~/Tournament/Index">Lista turniejów</a>